[package]
name = "stablecoin_prototype"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.16.0"
ic-cdk-macros = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
candid = "0.10"
ic-stable-structures = "0.6.5"
